# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Contact: support@gooddata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from gooddata_api_client.models.aac_visualization_widget_all_of_description import AacVisualizationWidgetAllOfDescription
from gooddata_api_client.models.aac_visualization_widget_all_of_title import AacVisualizationWidgetAllOfTitle
from gooddata_api_client.models.aac_widget_size import AacWidgetSize
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AacVisualizationWidget(BaseModel):
    """
    AacVisualizationWidget
    """ # noqa: E501
    additional_properties: Optional[Dict[str, Optional[Dict[str, Any]]]] = Field(default=None, alias="additionalProperties")
    columns: Optional[StrictInt] = Field(default=None, description="Widget width in grid columns (GAAC).")
    container: Optional[StrictStr] = Field(default=None, description="Container widget identifier.")
    content: Optional[StrictStr] = Field(default=None, description="Rich text content.")
    var_date: Optional[StrictStr] = Field(default=None, description="Date dataset for filtering.", alias="date")
    description: Optional[AacVisualizationWidgetAllOfDescription] = None
    drill_down: Optional[Dict[str, Any]] = Field(default=None, description="Free-form JSON object")
    enable_section_headers: Optional[StrictBool] = Field(default=None, description="Whether section headers are enabled for container widgets.")
    ignore_dashboard_filters: Optional[List[StrictStr]] = Field(default=None, description="Deprecated. Use ignoredFilters instead.")
    ignored_filters: Optional[List[StrictStr]] = Field(default=None, description="A list of dashboard filters to be ignored for this widget (GAAC).")
    interactions: Optional[List[Optional[Dict[str, Any]]]] = Field(default=None, description="Widget interactions (GAAC).")
    layout_direction: Optional[StrictStr] = Field(default=None, description="Layout direction for container widgets.")
    metric: Optional[StrictStr] = Field(default=None, description="Inline metric reference.")
    rows: Optional[StrictInt] = Field(default=None, description="Widget height in grid rows (GAAC).")
    sections: Optional[List[AacSection]] = Field(default=None, description="Nested sections for layout widgets.")
    size: Optional[AacWidgetSize] = None
    title: Optional[AacVisualizationWidgetAllOfTitle] = None
    type: Optional[StrictStr] = Field(default=None, description="Widget type.")
    visualization: StrictStr = Field(description="Visualization ID reference.")
    visualizations: Optional[List[AacWidget]] = Field(default=None, description="Visualization switcher items.")
    zoom_data: Optional[StrictBool] = Field(default=None, description="Enable zooming to the data for certain visualization types (GAAC).")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["additionalProperties", "columns", "container", "content", "date", "description", "drill_down", "enable_section_headers", "ignore_dashboard_filters", "ignored_filters", "interactions", "layout_direction", "metric", "rows", "sections", "size", "title", "type", "visualization", "visualizations", "zoom_data"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AacVisualizationWidget from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of description
        if self.description:
            _dict['description'] = self.description.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in sections (list)
        _items = []
        if self.sections:
            for _item_sections in self.sections:
                if _item_sections:
                    _items.append(_item_sections.to_dict())
            _dict['sections'] = _items
        # override the default output from pydantic by calling `to_dict()` of size
        if self.size:
            _dict['size'] = self.size.to_dict()
        # override the default output from pydantic by calling `to_dict()` of title
        if self.title:
            _dict['title'] = self.title.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in visualizations (list)
        _items = []
        if self.visualizations:
            for _item_visualizations in self.visualizations:
                if _item_visualizations:
                    _items.append(_item_visualizations.to_dict())
            _dict['visualizations'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if drill_down (nullable) is None
        # and model_fields_set contains the field
        if self.drill_down is None and "drill_down" in self.model_fields_set:
            _dict['drill_down'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AacVisualizationWidget from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "additionalProperties": obj.get("additionalProperties"),
            "columns": obj.get("columns"),
            "container": obj.get("container"),
            "content": obj.get("content"),
            "date": obj.get("date"),
            "description": AacVisualizationWidgetAllOfDescription.from_dict(obj["description"]) if obj.get("description") is not None else None,
            "drill_down": obj.get("drill_down"),
            "enable_section_headers": obj.get("enable_section_headers"),
            "ignore_dashboard_filters": obj.get("ignore_dashboard_filters"),
            "ignored_filters": obj.get("ignored_filters"),
            "interactions": obj.get("interactions"),
            "layout_direction": obj.get("layout_direction"),
            "metric": obj.get("metric"),
            "rows": obj.get("rows"),
            "sections": [AacSection.from_dict(_item) for _item in obj["sections"]] if obj.get("sections") is not None else None,
            "size": AacWidgetSize.from_dict(obj["size"]) if obj.get("size") is not None else None,
            "title": AacVisualizationWidgetAllOfTitle.from_dict(obj["title"]) if obj.get("title") is not None else None,
            "type": obj.get("type"),
            "visualization": obj.get("visualization"),
            "visualizations": [AacWidget.from_dict(_item) for _item in obj["visualizations"]] if obj.get("visualizations") is not None else None,
            "zoom_data": obj.get("zoom_data")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj

from gooddata_api_client.models.aac_section import AacSection
from gooddata_api_client.models.aac_widget import AacWidget
# TODO: Rewrite to not use raise_errors
AacVisualizationWidget.model_rebuild(raise_errors=False)

