# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Contact: support@gooddata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator, model_serializer
from typing import Any, List, Optional
from gooddata_api_client.models.aac_dashboard_plugin_link import AacDashboardPluginLink
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

AACDASHBOARDWITHTABSALLOFPLUGINS_ONE_OF_SCHEMAS = ["AacDashboardPluginLink", "str"]

class AacDashboardWithTabsAllOfPlugins(BaseModel):
    """
    AacDashboardWithTabsAllOfPlugins
    """
    # data type: str
    oneof_schema_1_validator: Optional[StrictStr] = None
    # data type: AacDashboardPluginLink
    oneof_schema_2_validator: Optional[AacDashboardPluginLink] = None
    actual_instance: Optional[Union[AacDashboardPluginLink, str]] = None
    one_of_schemas: Set[str] = { "AacDashboardPluginLink", "str" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )

    # _PATCHED_ONEOF_SERIALIZER by scripts/postgen_api_client.py: dump
    # the inner variant directly so SDK code that walks model_dump
    # output sees the wire-format payload, not the envelope. The
    # serializer respects the parent dump's ``exclude_none`` /
    # ``exclude_unset`` flags by passing through ``info``.
    @model_serializer(mode='wrap')
    def _serialize_oneof(self, handler, info):
        if self.actual_instance is None:
            return None
        if hasattr(self.actual_instance, 'model_dump'):
            return self.actual_instance.model_dump(
                by_alias=info.by_alias if info.by_alias is not None else True,
                exclude_none=info.exclude_none,
                exclude_unset=info.exclude_unset,
            )
        return self.actual_instance



    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = AacDashboardWithTabsAllOfPlugins.model_construct()
        error_messages = []
        match = 0
        # validate data type: str
        try:
            instance.oneof_schema_1_validator = v
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # validate data type: AacDashboardPluginLink
        if not isinstance(v, AacDashboardPluginLink):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AacDashboardPluginLink`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in AacDashboardWithTabsAllOfPlugins with oneOf schemas: AacDashboardPluginLink, str. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in AacDashboardWithTabsAllOfPlugins with oneOf schemas: AacDashboardPluginLink, str. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        # PATCHED-ONEOF-FROM-JSON by scripts/postgen_api_client.py:
        #   The default v7 dispatcher tries every variant and raises
        #   'Multiple matches' when more than one validates — common
        #   when no variant marks a discriminator field as required.
        #   Pick the variant whose *unique* alias key is present in
        #   the input; fall back to first-validates-wins.
        instance = cls.model_construct()
        try:
            obj = json.loads(json_str)
        except (TypeError, ValueError):
            obj = None

        variant_classes = [
            v for v in (
                AacDashboardPluginLink,
                str,
            ) if v is not None
        ]

        def _alias_keys(variant):
            keys = set()
            for fname, finfo in getattr(variant, 'model_fields', {}).items():
                if fname == 'additional_properties':
                    continue
                keys.add(finfo.alias or fname)
            return keys

        variant_aliases = [_alias_keys(v) for v in variant_classes]
        # A key is a discriminator when it is unique to a single variant.
        union = set().union(*variant_aliases) if variant_aliases else set()
        shared = set()
        for ks in variant_aliases:
            for k in ks:
                if sum(k in other for other in variant_aliases) > 1:
                    shared.add(k)
        unique_per_variant = [ks - shared for ks in variant_aliases]

        if isinstance(obj, dict):
            input_keys = set(obj.keys())
            for variant, unique in zip(variant_classes, unique_per_variant):
                if unique and any(k in input_keys for k in unique):
                    instance.actual_instance = variant.from_json(json_str)
                    return instance

        # Fallback: try each variant in turn; first successful parse
        # wins (matches the legacy ``python-prior`` permissive behaviour).
        for variant in variant_classes:
            try:
                instance.actual_instance = variant.from_json(json_str)
                return instance
            except (ValidationError, ValueError):
                continue
        raise ValueError(
            "No match found when deserializing the JSON string into AacDashboardWithTabsAllOfPlugins"
            " with oneOf schemas: AacDashboardPluginLink, str"
        )

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], AacDashboardPluginLink, str]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


