# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Contact: support@gooddata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List
from gooddata_api_client.models.organization_cache_usage import OrganizationCacheUsage
from gooddata_api_client.models.workspace_cache_usage import WorkspaceCacheUsage
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CacheUsageData(BaseModel):
    """
    Result of scan of data source physical model.
    """ # noqa: E501
    organization_cache_usage: OrganizationCacheUsage = Field(alias="organizationCacheUsage")
    workspace_cache_usages: Dict[str, WorkspaceCacheUsage] = Field(description="Map of data about the cache usage of the individual workspaces.", alias="workspaceCacheUsages")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["organizationCacheUsage", "workspaceCacheUsages"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CacheUsageData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of organization_cache_usage
        if self.organization_cache_usage:
            _dict['organizationCacheUsage'] = self.organization_cache_usage.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each value in workspace_cache_usages (dict)
        _field_dict = {}
        if self.workspace_cache_usages:
            for _key_workspace_cache_usages in self.workspace_cache_usages:
                if self.workspace_cache_usages[_key_workspace_cache_usages]:
                    _field_dict[_key_workspace_cache_usages] = self.workspace_cache_usages[_key_workspace_cache_usages].to_dict()
            _dict['workspaceCacheUsages'] = _field_dict
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CacheUsageData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "organizationCacheUsage": OrganizationCacheUsage.from_dict(obj["organizationCacheUsage"]) if obj.get("organizationCacheUsage") is not None else None,
            "workspaceCacheUsages": dict(
                (_k, WorkspaceCacheUsage.from_dict(_v))
                for _k, _v in obj["workspaceCacheUsages"].items()
            )
            if obj.get("workspaceCacheUsages") is not None
            else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


