# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Contact: support@gooddata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List
from gooddata_api_client.models.attribute_item import AttributeItem
from gooddata_api_client.models.change_analysis_params_filters_inner import ChangeAnalysisParamsFiltersInner
from gooddata_api_client.models.measure_item import MeasureItem
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ChangeAnalysisParams(BaseModel):
    """
    Change analysis specification.
    """ # noqa: E501
    analyzed_period: StrictStr = Field(description="The analyzed time period", alias="analyzedPeriod")
    attributes: List[AttributeItem] = Field(description="Attributes to analyze for significant changes")
    date_attribute: AttributeItem = Field(alias="dateAttribute")
    filters: List[ChangeAnalysisParamsFiltersInner] = Field(description="Optional filters to apply")
    measure: MeasureItem
    measure_title: StrictStr = Field(description="The title of the measure being analyzed", alias="measureTitle")
    reference_period: StrictStr = Field(description="The reference time period", alias="referencePeriod")
    use_smart_attribute_selection: StrictBool = Field(description="Whether to use smart attribute selection", alias="useSmartAttributeSelection")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["analyzedPeriod", "attributes", "dateAttribute", "filters", "measure", "measureTitle", "referencePeriod", "useSmartAttributeSelection"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ChangeAnalysisParams from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in attributes (list)
        _items = []
        if self.attributes:
            for _item_attributes in self.attributes:
                if _item_attributes:
                    _items.append(_item_attributes.to_dict())
            _dict['attributes'] = _items
        # override the default output from pydantic by calling `to_dict()` of date_attribute
        if self.date_attribute:
            _dict['dateAttribute'] = self.date_attribute.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in filters (list)
        _items = []
        if self.filters:
            for _item_filters in self.filters:
                if _item_filters:
                    _items.append(_item_filters.to_dict())
            _dict['filters'] = _items
        # override the default output from pydantic by calling `to_dict()` of measure
        if self.measure:
            _dict['measure'] = self.measure.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ChangeAnalysisParams from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "analyzedPeriod": obj.get("analyzedPeriod"),
            "attributes": [AttributeItem.from_dict(_item) for _item in obj["attributes"]] if obj.get("attributes") is not None else None,
            "dateAttribute": AttributeItem.from_dict(obj["dateAttribute"]) if obj.get("dateAttribute") is not None else None,
            "filters": [ChangeAnalysisParamsFiltersInner.from_dict(_item) for _item in obj["filters"]] if obj.get("filters") is not None else None,
            "measure": MeasureItem.from_dict(obj["measure"]) if obj.get("measure") is not None else None,
            "measureTitle": obj.get("measureTitle"),
            "referencePeriod": obj.get("referencePeriod"),
            "useSmartAttributeSelection": obj.get("useSmartAttributeSelection")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


