# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Contact: support@gooddata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CsvParseOptions(BaseModel):
    """
    Options for parsing CSV files.
    """ # noqa: E501
    delimiter: Optional[StrictStr] = Field(default=None, description="The character delimiting individual cells in the CSV data.")
    double_quote: Optional[StrictBool] = Field(default=None, description="Whether two quotes in a quoted CSV value denote a single quote in the data.", alias="doubleQuote")
    escape_char: Optional[Dict[str, Any]] = Field(default=None, description="The character used optionally for escaping special characters or false to disable escaping.", alias="escapeChar")
    ignore_empty_lines: Optional[StrictBool] = Field(default=None, description="Whether empty lines are ignored in CSV input.", alias="ignoreEmptyLines")
    newlines_in_values: Optional[StrictBool] = Field(default=None, description="Whether newline characters are allowed in CSV values.", alias="newlinesInValues")
    quote_char: Optional[Dict[str, Any]] = Field(default=None, description="The character used optionally for quoting CSV values or false to disable quoting.", alias="quoteChar")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["delimiter", "doubleQuote", "escapeChar", "ignoreEmptyLines", "newlinesInValues", "quoteChar"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CsvParseOptions from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CsvParseOptions from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "delimiter": obj.get("delimiter"),
            "doubleQuote": obj.get("doubleQuote"),
            "escapeChar": obj.get("escapeChar"),
            "ignoreEmptyLines": obj.get("ignoreEmptyLines"),
            "newlinesInValues": obj.get("newlinesInValues"),
            "quoteChar": obj.get("quoteChar")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


