# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Contact: support@gooddata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from gooddata_api_client.models.sort_key import SortKey
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Dimension(BaseModel):
    """
    Single dimension description.
    """ # noqa: E501
    item_identifiers: List[StrictStr] = Field(description="List of items in current dimension. Can reference 'localIdentifier' from 'AttributeItem', or special pseudo attribute \"measureGroup\" representing list of metrics.", alias="itemIdentifiers")
    local_identifier: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Dimension identification within requests. Other entities can reference this dimension by this value.", alias="localIdentifier")
    sorting: Optional[List[SortKey]] = Field(default=None, description="List of sorting rules. From most relevant to least relevant (less relevant rule is applied, when more relevant rule compares items as equal).")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["itemIdentifiers", "localIdentifier", "sorting"]

    @field_validator('local_identifier')
    def local_identifier_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[.a-zA-Z0-9_-]+$", value):
            raise ValueError(r"must validate the regular expression /^[.a-zA-Z0-9_-]+$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Dimension from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in sorting (list)
        _items = []
        if self.sorting:
            for _item_sorting in self.sorting:
                if _item_sorting:
                    _items.append(_item_sorting.to_dict())
            _dict['sorting'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Dimension from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "itemIdentifiers": obj.get("itemIdentifiers"),
            "localIdentifier": obj.get("localIdentifier"),
            "sorting": [SortKey.from_dict(_item) for _item in obj["sorting"]] if obj.get("sorting") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


