# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Contact: support@gooddata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from gooddata_api_client.models.json_api_llm_provider_in_attributes_models_inner import JsonApiLlmProviderInAttributesModelsInner
from gooddata_api_client.models.json_api_llm_provider_in_attributes_provider_config import JsonApiLlmProviderInAttributesProviderConfig
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class JsonApiLlmProviderInAttributes(BaseModel):
    """
    JsonApiLlmProviderInAttributes
    """ # noqa: E501
    default_model_id: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="Required ID of the default model to use from the models list.", alias="defaultModelId")
    description: Optional[Annotated[str, Field(strict=True, max_length=10000)]] = Field(default=None, description="Description of the LLM Provider.")
    models: Optional[List[JsonApiLlmProviderInAttributesModelsInner]] = Field(default=None, description="List of LLM models available for this provider.")
    name: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    provider_config: Optional[JsonApiLlmProviderInAttributesProviderConfig] = Field(default=None, alias="providerConfig")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["defaultModelId", "description", "models", "name", "providerConfig"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JsonApiLlmProviderInAttributes from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in models (list)
        _items = []
        if self.models:
            for _item_models in self.models:
                if _item_models:
                    _items.append(_item_models.to_dict())
            _dict['models'] = _items
        # override the default output from pydantic by calling `to_dict()` of provider_config
        if self.provider_config:
            _dict['providerConfig'] = self.provider_config.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if default_model_id (nullable) is None
        # and model_fields_set contains the field
        if self.default_model_id is None and "default_model_id" in self.model_fields_set:
            _dict['defaultModelId'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if models (nullable) is None
        # and model_fields_set contains the field
        if self.models is None and "models" in self.model_fields_set:
            _dict['models'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if provider_config (nullable) is None
        # and model_fields_set contains the field
        if self.provider_config is None and "provider_config" in self.model_fields_set:
            _dict['providerConfig'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JsonApiLlmProviderInAttributes from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "defaultModelId": obj.get("defaultModelId"),
            "description": obj.get("description"),
            "models": [JsonApiLlmProviderInAttributesModelsInner.from_dict(_item) for _item in obj["models"]] if obj.get("models") is not None else None,
            "name": obj.get("name"),
            "providerConfig": JsonApiLlmProviderInAttributesProviderConfig.from_dict(obj["providerConfig"]) if obj.get("providerConfig") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


