# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Contact: support@gooddata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from gooddata_api_client.models.json_api_organization_out_attributes_cache_settings import JsonApiOrganizationOutAttributesCacheSettings
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class JsonApiOrganizationOutAttributes(BaseModel):
    """
    JsonApiOrganizationOutAttributes
    """ # noqa: E501
    allowed_origins: Optional[List[StrictStr]] = Field(default=None, alias="allowedOrigins")
    cache_settings: Optional[JsonApiOrganizationOutAttributesCacheSettings] = Field(default=None, alias="cacheSettings")
    data_center: Optional[StrictStr] = Field(default=None, description="Current deployment region. Should be used for issue investigation only.", alias="dataCenter")
    early_access: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="The early access feature identifier. It is used to enable experimental features. Deprecated in favor of earlyAccessValues.", alias="earlyAccess")
    early_access_values: Optional[List[Annotated[str, Field(strict=True, max_length=255)]]] = Field(default=None, description="The early access feature identifiers. They are used to enable experimental features.", alias="earlyAccessValues")
    hostname: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    name: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    region: Optional[StrictStr] = Field(default=None, description="Current deployment cluster name. Should be used for issue investigation only.")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["allowedOrigins", "cacheSettings", "dataCenter", "earlyAccess", "earlyAccessValues", "hostname", "name", "region"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JsonApiOrganizationOutAttributes from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of cache_settings
        if self.cache_settings:
            _dict['cacheSettings'] = self.cache_settings.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if data_center (nullable) is None
        # and model_fields_set contains the field
        if self.data_center is None and "data_center" in self.model_fields_set:
            _dict['dataCenter'] = None

        # set to None if early_access (nullable) is None
        # and model_fields_set contains the field
        if self.early_access is None and "early_access" in self.model_fields_set:
            _dict['earlyAccess'] = None

        # set to None if early_access_values (nullable) is None
        # and model_fields_set contains the field
        if self.early_access_values is None and "early_access_values" in self.model_fields_set:
            _dict['earlyAccessValues'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if region (nullable) is None
        # and model_fields_set contains the field
        if self.region is None and "region" in self.model_fields_set:
            _dict['region'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JsonApiOrganizationOutAttributes from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "allowedOrigins": obj.get("allowedOrigins"),
            "cacheSettings": JsonApiOrganizationOutAttributesCacheSettings.from_dict(obj["cacheSettings"]) if obj.get("cacheSettings") is not None else None,
            "dataCenter": obj.get("dataCenter"),
            "earlyAccess": obj.get("earlyAccess"),
            "earlyAccessValues": obj.get("earlyAccessValues"),
            "hostname": obj.get("hostname"),
            "name": obj.get("name"),
            "region": obj.get("region")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


