# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Contact: support@gooddata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from gooddata_api_client.models.json_api_analytical_dashboard_out_relationships_certified_by import JsonApiAnalyticalDashboardOutRelationshipsCertifiedBy
from gooddata_api_client.models.json_api_automation_in_relationships_analytical_dashboard import JsonApiAutomationInRelationshipsAnalyticalDashboard
from gooddata_api_client.models.json_api_automation_in_relationships_export_definitions import JsonApiAutomationInRelationshipsExportDefinitions
from gooddata_api_client.models.json_api_automation_in_relationships_notification_channel import JsonApiAutomationInRelationshipsNotificationChannel
from gooddata_api_client.models.json_api_automation_in_relationships_recipients import JsonApiAutomationInRelationshipsRecipients
from gooddata_api_client.models.json_api_automation_out_relationships_automation_results import JsonApiAutomationOutRelationshipsAutomationResults
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class JsonApiAutomationOutRelationships(BaseModel):
    """
    JsonApiAutomationOutRelationships
    """ # noqa: E501
    analytical_dashboard: Optional[JsonApiAutomationInRelationshipsAnalyticalDashboard] = Field(default=None, alias="analyticalDashboard")
    automation_results: Optional[JsonApiAutomationOutRelationshipsAutomationResults] = Field(default=None, alias="automationResults")
    created_by: Optional[JsonApiAnalyticalDashboardOutRelationshipsCertifiedBy] = Field(default=None, alias="createdBy")
    export_definitions: Optional[JsonApiAutomationInRelationshipsExportDefinitions] = Field(default=None, alias="exportDefinitions")
    modified_by: Optional[JsonApiAnalyticalDashboardOutRelationshipsCertifiedBy] = Field(default=None, alias="modifiedBy")
    notification_channel: Optional[JsonApiAutomationInRelationshipsNotificationChannel] = Field(default=None, alias="notificationChannel")
    recipients: Optional[JsonApiAutomationInRelationshipsRecipients] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["analyticalDashboard", "automationResults", "createdBy", "exportDefinitions", "modifiedBy", "notificationChannel", "recipients"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JsonApiAutomationOutRelationships from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of analytical_dashboard
        if self.analytical_dashboard:
            _dict['analyticalDashboard'] = self.analytical_dashboard.to_dict()
        # override the default output from pydantic by calling `to_dict()` of automation_results
        if self.automation_results:
            _dict['automationResults'] = self.automation_results.to_dict()
        # override the default output from pydantic by calling `to_dict()` of created_by
        if self.created_by:
            _dict['createdBy'] = self.created_by.to_dict()
        # override the default output from pydantic by calling `to_dict()` of export_definitions
        if self.export_definitions:
            _dict['exportDefinitions'] = self.export_definitions.to_dict()
        # override the default output from pydantic by calling `to_dict()` of modified_by
        if self.modified_by:
            _dict['modifiedBy'] = self.modified_by.to_dict()
        # override the default output from pydantic by calling `to_dict()` of notification_channel
        if self.notification_channel:
            _dict['notificationChannel'] = self.notification_channel.to_dict()
        # override the default output from pydantic by calling `to_dict()` of recipients
        if self.recipients:
            _dict['recipients'] = self.recipients.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JsonApiAutomationOutRelationships from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "analyticalDashboard": JsonApiAutomationInRelationshipsAnalyticalDashboard.from_dict(obj["analyticalDashboard"]) if obj.get("analyticalDashboard") is not None else None,
            "automationResults": JsonApiAutomationOutRelationshipsAutomationResults.from_dict(obj["automationResults"]) if obj.get("automationResults") is not None else None,
            "createdBy": JsonApiAnalyticalDashboardOutRelationshipsCertifiedBy.from_dict(obj["createdBy"]) if obj.get("createdBy") is not None else None,
            "exportDefinitions": JsonApiAutomationInRelationshipsExportDefinitions.from_dict(obj["exportDefinitions"]) if obj.get("exportDefinitions") is not None else None,
            "modifiedBy": JsonApiAnalyticalDashboardOutRelationshipsCertifiedBy.from_dict(obj["modifiedBy"]) if obj.get("modifiedBy") is not None else None,
            "notificationChannel": JsonApiAutomationInRelationshipsNotificationChannel.from_dict(obj["notificationChannel"]) if obj.get("notificationChannel") is not None else None,
            "recipients": JsonApiAutomationInRelationshipsRecipients.from_dict(obj["recipients"]) if obj.get("recipients") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


