# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Contact: support@gooddata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class JsonApiMemoryItemOutAttributes(BaseModel):
    """
    JsonApiMemoryItemOutAttributes
    """ # noqa: E501
    are_relations_valid: Optional[StrictBool] = Field(default=None, alias="areRelationsValid")
    created_at: Optional[datetime] = Field(default=None, description="Time of the entity creation.", alias="createdAt")
    description: Optional[Annotated[str, Field(strict=True, max_length=10000)]] = None
    instruction: Annotated[str, Field(strict=True, max_length=255)] = Field(description="The text that will be injected into the system prompt")
    is_disabled: Optional[StrictBool] = Field(default=None, description="Whether memory item is disabled", alias="isDisabled")
    keywords: Optional[List[StrictStr]] = Field(default=None, description="Set of unique strings used for semantic similarity filtering")
    modified_at: Optional[datetime] = Field(default=None, description="Time of the last entity modification.", alias="modifiedAt")
    strategy: StrictStr = Field(description="Strategy defining when the memory item should be applied")
    tags: Optional[List[StrictStr]] = None
    title: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["areRelationsValid", "createdAt", "description", "instruction", "isDisabled", "keywords", "modifiedAt", "strategy", "tags", "title"]

    @field_validator('created_at')
    def created_at_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}", value):
            raise ValueError(r"must validate the regular expression /[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}/")
        return value

    @field_validator('modified_at')
    def modified_at_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}", value):
            raise ValueError(r"must validate the regular expression /[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}/")
        return value

    @field_validator('strategy')
    def strategy_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['ALWAYS', 'AUTO']):
            raise ValueError("must be one of enum values ('ALWAYS', 'AUTO')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JsonApiMemoryItemOutAttributes from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if created_at (nullable) is None
        # and model_fields_set contains the field
        if self.created_at is None and "created_at" in self.model_fields_set:
            _dict['createdAt'] = None

        # set to None if modified_at (nullable) is None
        # and model_fields_set contains the field
        if self.modified_at is None and "modified_at" in self.model_fields_set:
            _dict['modifiedAt'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JsonApiMemoryItemOutAttributes from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "areRelationsValid": obj.get("areRelationsValid"),
            "createdAt": obj.get("createdAt"),
            "description": obj.get("description"),
            "instruction": obj.get("instruction"),
            "isDisabled": obj.get("isDisabled"),
            "keywords": obj.get("keywords"),
            "modifiedAt": obj.get("modifiedAt"),
            "strategy": obj.get("strategy"),
            "tags": obj.get("tags"),
            "title": obj.get("title")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


