# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Contact: support@gooddata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from gooddata_api_client.models.json_api_aggregated_fact_out_relationships_dataset import JsonApiAggregatedFactOutRelationshipsDataset
from gooddata_api_client.models.json_api_analytical_dashboard_out_relationships_labels import JsonApiAnalyticalDashboardOutRelationshipsLabels
from gooddata_api_client.models.json_api_attribute_out_relationships_attribute_hierarchies import JsonApiAttributeOutRelationshipsAttributeHierarchies
from gooddata_api_client.models.json_api_attribute_out_relationships_default_view import JsonApiAttributeOutRelationshipsDefaultView
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class JsonApiAttributeOutRelationships(BaseModel):
    """
    JsonApiAttributeOutRelationships
    """ # noqa: E501
    attribute_hierarchies: Optional[JsonApiAttributeOutRelationshipsAttributeHierarchies] = Field(default=None, alias="attributeHierarchies")
    dataset: Optional[JsonApiAggregatedFactOutRelationshipsDataset] = None
    default_view: Optional[JsonApiAttributeOutRelationshipsDefaultView] = Field(default=None, alias="defaultView")
    labels: Optional[JsonApiAnalyticalDashboardOutRelationshipsLabels] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["attributeHierarchies", "dataset", "defaultView", "labels"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JsonApiAttributeOutRelationships from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of attribute_hierarchies
        if self.attribute_hierarchies:
            _dict['attributeHierarchies'] = self.attribute_hierarchies.to_dict()
        # override the default output from pydantic by calling `to_dict()` of dataset
        if self.dataset:
            _dict['dataset'] = self.dataset.to_dict()
        # override the default output from pydantic by calling `to_dict()` of default_view
        if self.default_view:
            _dict['defaultView'] = self.default_view.to_dict()
        # override the default output from pydantic by calling `to_dict()` of labels
        if self.labels:
            _dict['labels'] = self.labels.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JsonApiAttributeOutRelationships from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "attributeHierarchies": JsonApiAttributeOutRelationshipsAttributeHierarchies.from_dict(obj["attributeHierarchies"]) if obj.get("attributeHierarchies") is not None else None,
            "dataset": JsonApiAggregatedFactOutRelationshipsDataset.from_dict(obj["dataset"]) if obj.get("dataset") is not None else None,
            "defaultView": JsonApiAttributeOutRelationshipsDefaultView.from_dict(obj["defaultView"]) if obj.get("defaultView") is not None else None,
            "labels": JsonApiAnalyticalDashboardOutRelationshipsLabels.from_dict(obj["labels"]) if obj.get("labels") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


