# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Contact: support@gooddata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from gooddata_api_client.models.measure_item import MeasureItem
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class KeyDriversRequest(BaseModel):
    """
    KeyDriversRequest
    """ # noqa: E501
    aux_metrics: Optional[List[MeasureItem]] = Field(default=None, description="Additional metrics to be included in the computation, but excluded from the analysis.", alias="auxMetrics")
    metric: MeasureItem
    sort_direction: Optional[StrictStr] = Field(default='DESC', description="Sorting elements - ascending/descending order.", alias="sortDirection")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["auxMetrics", "metric", "sortDirection"]

    @field_validator('sort_direction')
    def sort_direction_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['ASC', 'DESC']):
            raise ValueError("must be one of enum values ('ASC', 'DESC')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of KeyDriversRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in aux_metrics (list)
        _items = []
        if self.aux_metrics:
            for _item_aux_metrics in self.aux_metrics:
                if _item_aux_metrics:
                    _items.append(_item_aux_metrics.to_dict())
            _dict['auxMetrics'] = _items
        # override the default output from pydantic by calling `to_dict()` of metric
        if self.metric:
            _dict['metric'] = self.metric.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of KeyDriversRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "auxMetrics": [MeasureItem.from_dict(_item) for _item in obj["auxMetrics"]] if obj.get("auxMetrics") is not None else None,
            "metric": MeasureItem.from_dict(obj["metric"]) if obj.get("metric") is not None else None,
            "sortDirection": obj.get("sortDirection") if obj.get("sortDirection") is not None else 'DESC'
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


