# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Contact: support@gooddata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class RelativeBoundedDateFilter(BaseModel):
    """
    RelativeBoundedDateFilter
    """ # noqa: E501
    var_from: Optional[StrictInt] = Field(default=None, alias="from")
    granularity: StrictStr
    to: Optional[StrictInt] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["from", "granularity", "to"]

    @field_validator('granularity')
    def granularity_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['ALL_TIME_GRANULARITY', 'GDC.time.year', 'GDC.time.week_us', 'GDC.time.week_in_year', 'GDC.time.week_in_quarter', 'GDC.time.week', 'GDC.time.euweek_in_year', 'GDC.time.euweek_in_quarter', 'GDC.time.quarter', 'GDC.time.quarter_in_year', 'GDC.time.month', 'GDC.time.month_in_quarter', 'GDC.time.month_in_year', 'GDC.time.day_in_year', 'GDC.time.day_in_quarter', 'GDC.time.day_in_month', 'GDC.time.day_in_week', 'GDC.time.day_in_euweek', 'GDC.time.date', 'GDC.time.hour', 'GDC.time.hour_in_day', 'GDC.time.minute', 'GDC.time.minute_in_hour', 'GDC.time.fiscal_month', 'GDC.time.fiscal_quarter', 'GDC.time.fiscal_year']):
            raise ValueError("must be one of enum values ('ALL_TIME_GRANULARITY', 'GDC.time.year', 'GDC.time.week_us', 'GDC.time.week_in_year', 'GDC.time.week_in_quarter', 'GDC.time.week', 'GDC.time.euweek_in_year', 'GDC.time.euweek_in_quarter', 'GDC.time.quarter', 'GDC.time.quarter_in_year', 'GDC.time.month', 'GDC.time.month_in_quarter', 'GDC.time.month_in_year', 'GDC.time.day_in_year', 'GDC.time.day_in_quarter', 'GDC.time.day_in_month', 'GDC.time.day_in_week', 'GDC.time.day_in_euweek', 'GDC.time.date', 'GDC.time.hour', 'GDC.time.hour_in_day', 'GDC.time.minute', 'GDC.time.minute_in_hour', 'GDC.time.fiscal_month', 'GDC.time.fiscal_quarter', 'GDC.time.fiscal_year')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RelativeBoundedDateFilter from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RelativeBoundedDateFilter from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "from": obj.get("from"),
            "granularity": obj.get("granularity"),
            "to": obj.get("to")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


