# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Contact: support@gooddata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SlidesExportRequest(BaseModel):
    """
    Export request object describing the export properties and metadata for slides exports.
    """ # noqa: E501
    dashboard_id: Optional[StrictStr] = Field(default=None, description="Dashboard identifier", alias="dashboardId")
    file_name: StrictStr = Field(description="File name to be used for retrieving the pdf document.", alias="fileName")
    format: StrictStr = Field(description="Requested resulting file type.")
    metadata: Optional[Dict[str, Any]] = Field(default=None, description="Free-form JSON object")
    template_id: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="Export template identifier.", alias="templateId")
    visualization_ids: Optional[Annotated[List[Annotated[str, Field(min_length=1, strict=True, max_length=255)]], Field(max_length=1)]] = Field(default=None, description="List of visualization ids to be exported. Note that only one visualization is currently supported.", alias="visualizationIds")
    widget_ids: Optional[Annotated[List[Annotated[str, Field(min_length=1, strict=True, max_length=255)]], Field(max_length=1)]] = Field(default=None, description="List of widget identifiers to be exported. Note that only one widget is currently supported.", alias="widgetIds")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["dashboardId", "fileName", "format", "metadata", "templateId", "visualizationIds", "widgetIds"]

    @field_validator('format')
    def format_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['PDF', 'PPTX']):
            raise ValueError("must be one of enum values ('PDF', 'PPTX')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SlidesExportRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if metadata (nullable) is None
        # and model_fields_set contains the field
        if self.metadata is None and "metadata" in self.model_fields_set:
            _dict['metadata'] = None

        # set to None if template_id (nullable) is None
        # and model_fields_set contains the field
        if self.template_id is None and "template_id" in self.model_fields_set:
            _dict['templateId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SlidesExportRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "dashboardId": obj.get("dashboardId"),
            "fileName": obj.get("fileName"),
            "format": obj.get("format"),
            "metadata": obj.get("metadata"),
            "templateId": obj.get("templateId"),
            "visualizationIds": obj.get("visualizationIds"),
            "widgetIds": obj.get("widgetIds")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


