# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Contact: support@gooddata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from gooddata_api_client.models.total_dimension import TotalDimension
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Total(BaseModel):
    """
    Definition of a total. There are two types of totals: grand totals and subtotals. Grand total data will be returned in a separate section of the result structure while subtotals are fully integrated into the main result data. The mechanism for this distinction is automatic and it's described in `TotalDimension`
    """ # noqa: E501
    function: StrictStr = Field(description="Aggregation function to compute the total.")
    local_identifier: StrictStr = Field(description="Total identification within this request. Used e.g. in sorting by a total.", alias="localIdentifier")
    metric: StrictStr = Field(description="The metric for which the total will be computed")
    total_dimensions: List[TotalDimension] = Field(alias="totalDimensions")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["function", "localIdentifier", "metric", "totalDimensions"]

    @field_validator('function')
    def function_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['SUM', 'MIN', 'MAX', 'AVG', 'MED', 'NAT']):
            raise ValueError("must be one of enum values ('SUM', 'MIN', 'MAX', 'AVG', 'MED', 'NAT')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Total from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in total_dimensions (list)
        _items = []
        if self.total_dimensions:
            for _item_total_dimensions in self.total_dimensions:
                if _item_total_dimensions:
                    _items.append(_item_total_dimensions.to_dict())
            _dict['totalDimensions'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Total from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "function": obj.get("function"),
            "localIdentifier": obj.get("localIdentifier"),
            "metric": obj.get("metric"),
            "totalDimensions": [TotalDimension.from_dict(_item) for _item in obj["totalDimensions"]] if obj.get("totalDimensions") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


