# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Contact: support@gooddata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TrendingObjectItem(BaseModel):
    """
    Trending analytics catalog objects
    """ # noqa: E501
    created_at: Optional[datetime] = Field(default=None, description="Timestamp when object was created.", alias="createdAt")
    created_by: Optional[StrictStr] = Field(default=None, description="ID of the user who created the object.", alias="createdBy")
    dataset_id: Optional[StrictStr] = Field(default=None, description="ID of the associated dataset, if applicable.", alias="datasetId")
    dataset_title: Optional[StrictStr] = Field(default=None, description="Title of the associated dataset, if applicable.", alias="datasetTitle")
    dataset_type: Optional[StrictStr] = Field(default=None, description="Type of the associated dataset, if applicable.", alias="datasetType")
    description: Optional[StrictStr] = Field(default=None, description="Object description.")
    id: StrictStr = Field(description="Object ID.")
    is_hidden: Optional[StrictBool] = Field(default=None, description="If true, this object is hidden from AI search results by default.", alias="isHidden")
    is_hidden_from_kda: Optional[StrictBool] = Field(default=None, description="If true, this object is hidden from KDA.", alias="isHiddenFromKda")
    metric_type: Optional[StrictStr] = Field(default=None, description="Type of the metric (e.g. MAQL), if applicable.", alias="metricType")
    modified_at: Optional[datetime] = Field(default=None, description="Timestamp when object was last modified.", alias="modifiedAt")
    modified_by: Optional[StrictStr] = Field(default=None, description="ID of the user who last modified the object.", alias="modifiedBy")
    tags: List[StrictStr]
    title: StrictStr = Field(description="Object title.")
    type: StrictStr = Field(description="Object type, e.g. dashboard, visualization, metric.")
    usage_count: StrictInt = Field(description="Number of times this object has been used/referenced.", alias="usageCount")
    visualization_url: Optional[StrictStr] = Field(default=None, description="URL of the visualization, if applicable.", alias="visualizationUrl")
    workspace_id: StrictStr = Field(description="Workspace ID the object belongs to.", alias="workspaceId")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["createdAt", "createdBy", "datasetId", "datasetTitle", "datasetType", "description", "id", "isHidden", "isHiddenFromKda", "metricType", "modifiedAt", "modifiedBy", "tags", "title", "type", "usageCount", "visualizationUrl", "workspaceId"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TrendingObjectItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TrendingObjectItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "createdAt": obj.get("createdAt"),
            "createdBy": obj.get("createdBy"),
            "datasetId": obj.get("datasetId"),
            "datasetTitle": obj.get("datasetTitle"),
            "datasetType": obj.get("datasetType"),
            "description": obj.get("description"),
            "id": obj.get("id"),
            "isHidden": obj.get("isHidden"),
            "isHiddenFromKda": obj.get("isHiddenFromKda"),
            "metricType": obj.get("metricType"),
            "modifiedAt": obj.get("modifiedAt"),
            "modifiedBy": obj.get("modifiedBy"),
            "tags": obj.get("tags"),
            "title": obj.get("title"),
            "type": obj.get("type"),
            "usageCount": obj.get("usageCount"),
            "visualizationUrl": obj.get("visualizationUrl"),
            "workspaceId": obj.get("workspaceId")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


