# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Contact: support@gooddata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from gooddata_api_client.models.anomaly_detection_config import AnomalyDetectionConfig
from gooddata_api_client.models.clustering_config import ClusteringConfig
from gooddata_api_client.models.forecast_config import ForecastConfig
from gooddata_api_client.models.what_if_scenario_config import WhatIfScenarioConfig
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class VisualizationConfig(BaseModel):
    """
    Visualization config for smart-function rendering.
    """ # noqa: E501
    anomaly_detection: Optional[AnomalyDetectionConfig] = Field(default=None, alias="anomalyDetection")
    clustering: Optional[ClusteringConfig] = None
    forecast: Optional[ForecastConfig] = None
    what_if: Optional[WhatIfScenarioConfig] = Field(default=None, alias="whatIf")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["anomalyDetection", "clustering", "forecast", "whatIf"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of VisualizationConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of anomaly_detection
        if self.anomaly_detection:
            _dict['anomalyDetection'] = self.anomaly_detection.to_dict()
        # override the default output from pydantic by calling `to_dict()` of clustering
        if self.clustering:
            _dict['clustering'] = self.clustering.to_dict()
        # override the default output from pydantic by calling `to_dict()` of forecast
        if self.forecast:
            _dict['forecast'] = self.forecast.to_dict()
        # override the default output from pydantic by calling `to_dict()` of what_if
        if self.what_if:
            _dict['whatIf'] = self.what_if.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of VisualizationConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "anomalyDetection": AnomalyDetectionConfig.from_dict(obj["anomalyDetection"]) if obj.get("anomalyDetection") is not None else None,
            "clustering": ClusteringConfig.from_dict(obj["clustering"]) if obj.get("clustering") is not None else None,
            "forecast": ForecastConfig.from_dict(obj["forecast"]) if obj.get("forecast") is not None else None,
            "whatIf": WhatIfScenarioConfig.from_dict(obj["whatIf"]) if obj.get("whatIf") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


