# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Contact: support@gooddata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Webhook(BaseModel):
    """
    Webhook
    """ # noqa: E501
    has_secret_key: Optional[StrictBool] = Field(default=None, description="Flag indicating if webhook has a hmac secret key.", alias="hasSecretKey")
    has_token: Optional[StrictBool] = Field(default=None, description="Flag indicating if webhook has a token.", alias="hasToken")
    secret_key: Optional[Annotated[str, Field(strict=True, max_length=10000)]] = Field(default=None, description="Hmac secret key for the webhook signature.", alias="secretKey")
    token: Optional[Annotated[str, Field(strict=True, max_length=10000)]] = Field(default=None, description="Bearer token for the webhook.")
    type: StrictStr = Field(description="The destination type.")
    url: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="The webhook URL.")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["hasSecretKey", "hasToken", "secretKey", "token", "type", "url"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['WEBHOOK']):
            raise ValueError("must be one of enum values ('WEBHOOK')")
        return value

    @field_validator('url')
    def url_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"https?\:\/\/.*", value):
            raise ValueError(r"must validate the regular expression /https?\:\/\/.*/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Webhook from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "has_secret_key",
            "has_token",
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if has_secret_key (nullable) is None
        # and model_fields_set contains the field
        if self.has_secret_key is None and "has_secret_key" in self.model_fields_set:
            _dict['hasSecretKey'] = None

        # set to None if has_token (nullable) is None
        # and model_fields_set contains the field
        if self.has_token is None and "has_token" in self.model_fields_set:
            _dict['hasToken'] = None

        # set to None if secret_key (nullable) is None
        # and model_fields_set contains the field
        if self.secret_key is None and "secret_key" in self.model_fields_set:
            _dict['secretKey'] = None

        # set to None if token (nullable) is None
        # and model_fields_set contains the field
        if self.token is None and "token" in self.model_fields_set:
            _dict['token'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Webhook from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "hasSecretKey": obj.get("hasSecretKey"),
            "hasToken": obj.get("hasToken"),
            "secretKey": obj.get("secretKey"),
            "token": obj.get("token"),
            "type": obj.get("type"),
            "url": obj.get("url")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


