# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Contact: support@gooddata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List
from gooddata_api_client.models.cache_removal_interval import CacheRemovalInterval
from gooddata_api_client.models.workspace_cache_settings import WorkspaceCacheSettings
from gooddata_api_client.models.workspace_current_cache_usage import WorkspaceCurrentCacheUsage
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class WorkspaceCacheUsage(BaseModel):
    """
    Data about a particular workspace cache usage.
    """ # noqa: E501
    current: WorkspaceCurrentCacheUsage
    removal_intervals: List[CacheRemovalInterval] = Field(description="List of cache removal intervals for workspace.", alias="removalIntervals")
    settings: WorkspaceCacheSettings
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["current", "removalIntervals", "settings"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WorkspaceCacheUsage from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of current
        if self.current:
            _dict['current'] = self.current.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in removal_intervals (list)
        _items = []
        if self.removal_intervals:
            for _item_removal_intervals in self.removal_intervals:
                if _item_removal_intervals:
                    _items.append(_item_removal_intervals.to_dict())
            _dict['removalIntervals'] = _items
        # override the default output from pydantic by calling `to_dict()` of settings
        if self.settings:
            _dict['settings'] = self.settings.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WorkspaceCacheUsage from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "current": WorkspaceCurrentCacheUsage.from_dict(obj["current"]) if obj.get("current") is not None else None,
            "removalIntervals": [CacheRemovalInterval.from_dict(_item) for _item in obj["removalIntervals"]] if obj.get("removalIntervals") is not None else None,
            "settings": WorkspaceCacheSettings.from_dict(obj["settings"]) if obj.get("settings") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


